version: '3.8'

services:
  web:
    build: .
    command: python server.py --reload --log-level debug
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mindtrack
      - DEBUG=True

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mindtrack
    ports:
      - "5432:5432"

volumes:
  postgres_data:
