services:
  # A web service for the Django application
  - type: web
    name: mindtrack
    env: python
    buildCommand: "./build_render.sh"
    startCommand: "gunicorn mindtrack.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --log-level info"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mindtrack.render_settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,mandtrack.onrender.com"
      - key: DATABASE_URL
        value: "postgresql://mindtrack_db_owner:npg_AUV4r3qElnDN@ep-steep-base-a2xkorr1-pooler.eu-central-1.aws.neon.tech/mindtrack_db?sslmode=require"
      - key: PYTHON_VERSION
        value: "3.10.0"
    healthCheckPath: /health/
    autoDeploy: true
