# Generated by Django 5.2 on 2025-05-03 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0003_completiontracker_completionevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('risk_factors', models.JSONField(blank=True, default=dict)),
                ('strengths', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('consultation_recommended', models.CharField(choices=[('not_required', 'Not Required'), ('recommended', 'Recommended'), ('required', 'Required'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='not_required', max_length=20)),
                ('consultation_notes', models.TextField(blank=True)),
                ('consultation_urgency', models.PositiveSmallIntegerField(default=0, help_text='1-10 scale, 10 being most urgent')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='feedback.response')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='assessments.assessment')),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status'], name='assessments_status_5e1f65_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['consultation_recommended'], name='assessments_consult_f13222_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['assessment_date'], name='assessments_assessm_235491_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='assessments_status_d8bde9_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['scheduled_date'], name='assessments_schedul_b4313a_idx'),
        ),
    ]
