# Generated by Django 5.2 on 2025-05-01 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('feedback', '0002_initial'),
        ('surveys', '0002_questiontype_alter_question_max_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('auto_analyze', models.BooleanField(default=False, help_text='Automatically analyze new responses')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Analysis parameters specific to this questionnaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_configs', to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_configurations', to='surveys.questionnaire')),
            ],
            options={
                'verbose_name': 'AI Analysis Configuration',
                'verbose_name_plural': 'AI Analysis Configurations',
                'ordering': ['questionnaire', 'ai_model'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField(help_text='Analysis results in JSON format')),
                ('summary', models.TextField(blank=True, help_text='Human-readable summary of the analysis')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence level of the analysis (0-1)', null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_analyses', to=settings.AUTH_USER_MODEL)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_results', to='analytics.aianalysisconfiguration')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='feedback.response')),
            ],
            options={
                'verbose_name': 'AI Analysis Result',
                'verbose_name_plural': 'AI Analysis Results',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('accuracy', 'Accuracy'), ('relevance', 'Relevance'), ('usefulness', 'Usefulness'), ('other', 'Other')], max_length=20)),
                ('rating', models.IntegerField(help_text='Rating from 1-5')),
                ('comments', models.TextField(blank=True)),
                ('provided_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='analytics.aianalysisresult')),
                ('provided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Feedback',
                'verbose_name_plural': 'AI Feedback',
                'ordering': ['-provided_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('sentiment', 'Sentiment Analysis'), ('classification', 'Classification'), ('clustering', 'Clustering'), ('regression', 'Regression'), ('nlp', 'Natural Language Processing'), ('custom', 'Custom Model')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Model configuration parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('insight_type', models.CharField(choices=[('trend', 'Trend'), ('anomaly', 'Anomaly'), ('pattern', 'Pattern'), ('recommendation', 'Recommendation'), ('prediction', 'Prediction'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10, null=True)),
                ('supporting_data', models.JSONField(blank=True, default=dict, help_text='Data supporting this insight')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='surveys.questionnaire')),
                ('related_responses', models.ManyToManyField(blank=True, related_name='insights', to='feedback.response')),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_insights', to='analytics.aimodel')),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aianalysisresult',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='analytics.aimodel'),
        ),
        migrations.AddField(
            model_name='aianalysisconfiguration',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_configurations', to='analytics.aimodel'),
        ),
        migrations.AlterUniqueTogether(
            name='aianalysisconfiguration',
            unique_together={('questionnaire', 'ai_model')},
        ),
    ]
