# Generated by Django 5.2 on 2025-05-01 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_aianalysisconfiguration_aianalysisresult_aifeedback_and_more'),
        ('groups', '0001_initial'),
        ('surveys', '0003_scoringsystem_scorerule_scorerange_optionscore_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='report',
            name='questionnaires',
        ),
        migrations.RemoveField(
            model_name='report',
            name='responses',
        ),
        migrations.AddField(
            model_name='report',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters used to generate the report'),
        ),
        migrations.AddField(
            model_name='report',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='surveys.questionnaire'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('response_summary', 'Response Summary'), ('trend_analysis', 'Trend Analysis'), ('ai_insights', 'AI Insights'), ('demographic_analysis', 'Demographic Analysis'), ('risk_assessment', 'Risk Assessment'), ('custom_export', 'Custom Export')], default='summary', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='groups.organization'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON'), ('html', 'HTML')], max_length=20),
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('response_summary', 'Response Summary'), ('trend_analysis', 'Trend Analysis'), ('ai_insights', 'AI Insights'), ('demographic_analysis', 'Demographic Analysis'), ('risk_assessment', 'Risk Assessment'), ('custom_export', 'Custom Export')], max_length=50)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON'), ('html', 'HTML')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parameters used to generate the report')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('next_run', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_schedules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules', to='groups.organization')),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules', to='surveys.questionnaire')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['next_run'],
            },
        ),
    ]
