# Generated by Django 5.2 on 2025-05-01 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_report_filters_remove_report_questionnaires_and_more'),
        ('feedback', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('analysis_type', models.CharField(choices=[('comprehensive', 'Comprehensive Analysis'), ('insights', 'Key Insights'), ('sentiment', 'Sentiment Analysis'), ('themes', 'Theme Identification'), ('patterns', 'Pattern Recognition')], default='comprehensive', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_responses', models.IntegerField(default=0)),
                ('processed_responses', models.IntegerField(default=0)),
                ('skipped_responses', models.IntegerField(default=0)),
                ('error_responses', models.IntegerField(default=0)),
                ('error_details', models.JSONField(default=list)),
                ('aggregate_insights', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batch_jobs', to=settings.AUTH_USER_MODEL)),
                ('responses', models.ManyToManyField(related_name='batch_jobs', to='feedback.response')),
            ],
            options={
                'verbose_name': 'Batch Analysis Job',
                'verbose_name_plural': 'Batch Analysis Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
