# Generated by Django 5.2 on 2025-05-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_batchanalysisjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF version of the report', null=True, upload_to='reports/pdf/'),
        ),
    ]
