# Generated by Django 5.2 on 2025-05-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
        ('surveys', '0003_scoringsystem_scorerule_scorerange_optionscore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.FloatField(default=0)),
                ('answers_required', models.PositiveIntegerField(default=0)),
                ('answers_provided', models.PositiveIntegerField(default=0)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_tracker', to='feedback.response')),
            ],
            options={
                'verbose_name': 'Completion Tracker',
                'verbose_name_plural': 'Completion Trackers',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CompletionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Started'), ('answer', 'Answered Question'), ('navigation', 'Navigation'), ('timeout', 'Timeout'), ('completion', 'Completed'), ('abandonment', 'Abandoned')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_events', to='feedback.answer')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_events', to='surveys.question')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='feedback.completiontracker')),
            ],
            options={
                'verbose_name': 'Completion Event',
                'verbose_name_plural': 'Completion Events',
                'ordering': ['timestamp'],
            },
        ),
    ]
