# Generated by Django 5.2 on 2025-05-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_add_questionnaire_field'),
        ('feedback', '0002_initial'),
    ]

    operations = [
    ]
