# Generated by Django 5.2 on 2025-05-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_aianalysis_advanced_fields'),
        ('feedback', '0003_completiontracker_completionevent'),
    ]

    operations = [
    ]
