# Generated by Django 5.2 on 2025-05-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_delete_emailschedule'),
        ('feedback', '0005_emailschedule'),
    ]

    operations = [
    ]
