# Generated by Django 5.2 on 2025-04-30 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('feedback', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='questionnaires',
            field=models.ManyToManyField(blank=True, related_name='reports', to='surveys.questionnaire'),
        ),
        migrations.AddField(
            model_name='report',
            name='responses',
            field=models.ManyToManyField(blank=True, related_name='reports', to='feedback.response'),
        ),
        migrations.AddField(
            model_name='widget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard'),
        ),
    ]
