# Generated by Django 5.2 on 2025-04-30 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('has_choices', models.BooleanField(default=False)),
                ('is_numeric', models.BooleanField(default=False)),
                ('is_text', models.BooleanField(default=False)),
                ('is_date', models.BooleanField(default=False)),
                ('is_file', models.BooleanField(default=False)),
                ('is_scorable', models.BooleanField(default=False)),
                ('default_max_score', models.FloatField(default=0)),
                ('default_scoring_weight', models.FloatField(default=1.0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Type',
                'verbose_name_plural': 'Question Types',
                'db_table': 'surveys_questiontype',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='scoring_weight',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='surveys.questiontype'),
        ),
    ]
