# Generated by Django 5.2 on 2025-05-06 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveysquestionnaire',
            name='slug',
        ),
    ]
