# Generated by Django 5.2 on 2025-05-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_remove_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysquestionnaire',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
