# Generated by Django 5.2 on 2025-05-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_emailschedule_bulk_options'),
        ('surveys', '0012_add_is_default_to_scoringsystem'),
    ]

    operations = [
    ]
