# Generated by Django 5.2 on 2025-05-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0014_add_is_template_field'),
        ('surveys', '0015_add_is_template_field_manual'),
    ]

    operations = [
    ]
