# Generated by Django 5.2 on 2025-05-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_merge_20250505_1540'),
        ('surveys', 'add_question_type_obj'),
    ]

    operations = [
    ]
