# Generated by Django 5.2 on 2025-04-30 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('groups', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='multiple_choices',
            field=models.ManyToManyField(blank=True, related_name='multiple_answers', to='surveys.questionchoice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='surveys.questionchoice'),
        ),
        migrations.AddField(
            model_name='response',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='groups.organization'),
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.questionnaire'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='feedback.response'),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='feedback.response'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['survey'], name='feedback_re_survey__a38b90_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['user'], name='feedback_re_user_id_c58b32_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['organization'], name='feedback_re_organiz_89393d_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['patient_identifier'], name='feedback_re_patient_6c662d_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['patient_email'], name='feedback_re_patient_1c7a06_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['risk_level'], name='feedback_re_risk_le_1f24d8_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['completed_at'], name='feedback_re_complet_596167_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['created_at'], name='feedback_re_created_04cf63_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['response'], name='feedback_an_respons_c77d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='feedback_an_questio_0bcc73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('response', 'question')},
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['response'], name='feedback_ai_respons_ca7e52_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['created_by'], name='feedback_ai_created_1a825d_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['created_at'], name='feedback_ai_created_876af5_idx'),
        ),
    ]
