# Generated by Django 5.2 on 2025-05-06 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaccess',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_accesses', to='surveys.surveysquestionnaire'),
        ),
        migrations.AlterUniqueTogether(
            name='memberaccess',
            unique_together={('member', 'questionnaire', 'access_code')},
        ),
    ]
